version: '3.8'
services:
  
  server:
    build: .
    ports:
      - 8008:8008
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8008

  redis:
    image: redis:alpine
    expose:
      - 6379

  celery:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/
    depends_on:
      - redis
    command: celery -A core worker -l INFO